version: "3.7"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mock_todo_db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin

  app:
    image: mock-todo-api
    ports:
      - 4000:3060
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mock_todo_db
    depends_on:
      - db
